import type { Lang } from "./language";

export const COPY = {
  en: {
    skip: "Skip to content",
    navShop: "Shop",
    navHours: "Hours",
    navVisit: "Visit",
    navReviews: "Reviews",
    navPhotos: "Photos",
    navStock: "What we carry",
    navHome: "Home",
    call: "Call",
    text: "Text",
    directions: "Directions",
    kicker: "Hispanic · American · Brazilian",
    headline: "Grocery, deli, and a butcher on Bridge Street.",
    lede: "Hispanic, American, and Brazilian products — rice, meats, household goods, and the things you came in for. SNAP/EBT welcome.",
    rating: "Google rating",
    reviews: "reviews",
    readReviews: "Read reviews on Google",
    snap: "SNAP / EBT",
    cards: "Credit cards",
    owned: "Woman-owned",
    openNow: "Open now",
    closedNow: "Closed now",
    hoursLabel: "Hours",
    hoursNote: "Nine to nine, every day. Holiday hours may vary — call ahead if you are unsure.",
    hoursRange: "9:00 AM – 9:00 PM",
    servicesTitle: "Services",
    visitTitle: "Come by the store",
    visitBody:
      "We are on Bridge Street in downtown Phoenixville, among the shops and restaurants. Street parking is nearby — reviewers call it a breeze.",
    mapTitle: "Map of Latino Mini Market on Bridge Street",
    deptsTitle: "What you’ll find",
    deptsLede:
      "A neighborhood grocery and a cultural hub — produce, the butcher, pantry staples, and goods from Mexico, Central America, South America, the Caribbean, and Brazil.",
    produceTitle: "Produce & deli",
    produceBody:
      "Fruit, vegetables, and a full deli case — cold cuts and the fresh things that belong on the table this week.",
    pantryTitle: "Aisle & pantry",
    pantryBody:
      "Tio João rice, Amafil tapioca, snacks, Mexican Coke, and imported groceries from Brazil, Mexico, and across Latin America.",
    meatsTitle: "Butcher shop",
    meatsBody:
      "A meat counter in back with fresh cuts and Brazilian linguica calabresa — ask at the case for what is in today.",
    homeTitle: "Household",
    homeBody:
      "Suavitel, Phebo soap, molcajetes, and the paper and kitchen staples you should not have to drive across town for.",
    aboutTitle: "A market for the neighborhood",
    aboutBody:
      "Latino Mini Market is a grocery, deli, and butcher on Bridge Street — a neighborhood store and a cultural hub. Authentic ingredients and pantry staples from Mexico, Central America, South America, the Caribbean, and Brazil. SNAP/EBT welcome.",
    videoTitle: "Walk up to the door",
    videoApproach: "From the sidewalk",
    videoWalkin: "Through the door",
    footerHours: "Open 9 AM – 9 PM daily",
    languages: "Languages",
    copyright: "Latino Mini Market. Phoenixville, Pennsylvania.",
    reviewsTitle: "What neighbors say",
    reviewsLede: "4.6 on Google from 35 reviews — a little bit of everything, and people who treat you well.",
    reviewsOnGoogle: "Google reviews",
    reviewsSummary: "Google review summary",
    open: "Open",
    closed: "Closed",
    closesAt: "Closes at",
    opensAt: "Opens at",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    callShop: "Call the shop",
    textShop: "Text the shop",
    reviewsPeople: "People keep coming back",
    reviewsWrite: "Write a Google review",
    reviewsGoogle: "See Google reviews",
    reviewsMore: "More reviews",
    reviewsLess: "Fewer reviews",
    photosTitle: "Photos",
    photosLede: "Aisles, the butcher case, and what is on the shelf this week.",
    photosAislesTitle: "Inside the store",
    photosCloseTitle: "Fresh counter & close-ups",
    pantryShotsTitle: "Latin pantry brands",
    pantryShotsLede:
      "Goya, Herdez, Embasa, Cacique, Ibarra, La Lechera — the packaged goods and fresh staples neighbors come in for.",
    signAlt: "Latino Mini Market sign — grocery, deli, butcher shop. Hispanic, American, and Brazilian products.",
  },
  es: {
    skip: "Saltar al contenido",
    navShop: "Tienda",
    navHours: "Horario",
    navVisit: "Visítanos",
    navReviews: "Reseñas",
    navPhotos: "Fotos",
    navStock: "Lo que tenemos",
    navHome: "Inicio",
    call: "Llamar",
    text: "Mensaje",
    directions: "Cómo llegar",
    kicker: "Hispano · Americano · Brasileño",
    headline: "Abarrotes, deli y carnicería en Bridge Street.",
    lede: "Productos hispanos, americanos y brasileños — arroz, carnes, artículos del hogar y lo que viniste a buscar. Aceptamos SNAP/EBT.",
    rating: "Calificación en Google",
    reviews: "reseñas",
    readReviews: "Ver reseñas en Google",
    snap: "SNAP / EBT",
    cards: "Tarjetas de crédito",
    owned: "Empresa de mujer",
    openNow: "Abierto ahora",
    closedNow: "Cerrado ahora",
    hoursLabel: "Horario",
    hoursNote:
      "De nueve a nueve, todos los días. En días festivos el horario puede cambiar — llama si tienes duda.",
    hoursRange: "9:00 a.m. – 9:00 p.m.",
    servicesTitle: "Servicios",
    visitTitle: "Ven a la tienda",
    visitBody:
      "Estamos en Bridge Street, en el centro de Phoenixville, entre tiendas y restaurantes. El estacionamiento en la calle es fácil — las reseñas lo dicen.",
    mapTitle: "Mapa de Latino Mini Market en Bridge Street",
    deptsTitle: "Lo que encuentras aquí",
    deptsLede:
      "Un mercado del barrio y un punto de encuentro — verdura, carnicería, abarrotes y productos de México, Centroamérica, Sudamérica, el Caraíbas y Brasil.",
    produceTitle: "Frescos y deli",
    produceBody:
      "Fruta, verdura y deli completo — fiambres y lo fresco que va en la mesa esta semana.",
    pantryTitle: "Abarrotes",
    pantryBody:
      "Arroz Tio João, tapioca Amafil, botanas, Coca mexicana y productos de Brasil, México y Latinoamérica.",
    meatsTitle: "Carnicería",
    meatsBody:
      "Mostrador de carnes al fondo, con cortes frescos y linguica calabresa brasileña — pregunta qué hay hoy.",
    homeTitle: "Hogar",
    homeBody:
      "Suavitel, jabón Phebo, molcajetes y lo básico de cocina, para no tener que cruzar el pueblo.",
    aboutTitle: "Un mercado del barrio",
    aboutBody:
      "Latino Mini Market es abarrotes, deli y carnicería en Bridge Street — tienda del barrio y punto de encuentro. Ingredientes de verdad y abarrotes de México, Centroamérica, Sudamérica, el Caraíbas y Brasil. Aceptamos SNAP/EBT.",
    videoTitle: "Camina hasta la puerta",
    videoApproach: "Desde la acera",
    videoWalkin: "Al entrar",
    footerHours: "Abierto de 9 a.m. a 9 p.m. todos los días",
    languages: "Idiomas",
    copyright: "Latino Mini Market. Phoenixville, Pensilvania.",
    reviewsTitle: "Lo que dice el barrio",
    reviewsLede: "4.6 en Google, 35 reseñas — un poco de todo, y gente que te atiende bien.",
    reviewsOnGoogle: "Reseñas en Google",
    reviewsSummary: "Resumen de reseñas de Google",
    open: "Abierto",
    closed: "Cerrado",
    closesAt: "Cierra a las",
    opensAt: "Abre a las",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    callShop: "Llamar a la tienda",
    textShop: "Mensaje a la tienda",
    reviewsPeople: "La gente vuelve",
    reviewsWrite: "Escribir una reseña en Google",
    reviewsGoogle: "Ver reseñas de Google",
    reviewsMore: "Más reseñas",
    reviewsLess: "Menos reseñas",
    photosTitle: "Fotos",
    photosLede: "Pasillos, la carnicería y lo que hay en el estante esta semana.",
    photosAislesTitle: "Por dentro de la tienda",
    photosCloseTitle: "Mostrador y detalle",
    pantryShotsTitle: "Marcas de la despensa",
    pantryShotsLede:
      "Goya, Herdez, Embasa, Cacique, Ibarra, La Lechera — abarrotes y lo fresco que busca el barrio.",
    signAlt: "Letrero de Latino Mini Market — abarrotes, deli, carnicería. Productos hispanos, americanos y brasileños.",
  },
  pt: {
    skip: "Saltar para o conteúdo",
    navShop: "Loja",
    navHours: "Horário",
    navVisit: "Visite",
    navReviews: "Avaliações",
    navPhotos: "Fotos",
    navStock: "O que temos",
    navHome: "Início",
    call: "Ligar",
    text: "Mensagem",
    directions: "Como chegar",
    kicker: "Hispânico · Americano · Brasileiro",
    headline: "Mercearia, deli e talho na Bridge Street.",
    lede: "Produtos hispânicos, americanos e brasileiros — arroz, carnes, artigos para casa e o que veio buscar. SNAP/EBT aceite.",
    rating: "Avaliação no Google",
    reviews: "avaliações",
    readReviews: "Ver avaliações no Google",
    snap: "SNAP / EBT",
    cards: "Cartões de crédito",
    owned: "Empresa de mulher",
    openNow: "Aberto agora",
    closedNow: "Fechado agora",
    hoursLabel: "Horário",
    hoursNote:
      "Das nove às nove, todos os dias. Em feriados o horário pode mudar — ligue se tiver dúvida.",
    hoursRange: "9:00 – 21:00",
    servicesTitle: "Serviços",
    visitTitle: "Venha à loja",
    visitBody:
      "Estamos na Bridge Street, no centro de Phoenixville, entre lojas e restaurantes. O estacionamento na rua é fácil — as avaliações dizem isso.",
    mapTitle: "Mapa do Latino Mini Market na Bridge Street",
    deptsTitle: "O que encontra aqui",
    deptsLede:
      "Uma mercearia do bairro e um ponto de encontro — hortifrúti, talho, mercearia e produtos do México, da América Central, da América do Sul, das Caraíbas e do Brasil.",
    produceTitle: "Hortifrúti e deli",
    produceBody:
      "Fruta, legumes e um deli completo — fiambre e o fresco que vai à mesa esta semana.",
    pantryTitle: "Mercearia",
    pantryBody:
      "Arroz Tio João, tapioca Amafil, snacks, Coca mexicana e produtos do Brasil, do México e da América Latina.",
    meatsTitle: "Talho",
    meatsBody:
      "Balcão de carnes ao fundo, com cortes frescos e linguiça calabresa brasileira — pergunte o que há hoje.",
    homeTitle: "Casa",
    homeBody:
      "Suavitel, sabonete Phebo, molcajetes e o básico de cozinha, para não ter de atravessar a vila.",
    aboutTitle: "Um mercado do bairro",
    aboutBody:
      "O Latino Mini Market é mercearia, deli e talho na Bridge Street — loja do bairro e ponto de encontro. Ingredientes autênticos e mercearia do México, da América Central, da América do Sul, das Caraíbas e do Brasil. Aceitamos SNAP/EBT.",
    videoTitle: "Caminhe até à porta",
    videoApproach: "Da calçada",
    videoWalkin: "A entrar",
    footerHours: "Aberto das 9:00 às 21:00 todos os dias",
    languages: "Idiomas",
    copyright: "Latino Mini Market. Phoenixville, Pensilvânia.",
    reviewsTitle: "O que diz o bairro",
    reviewsLede: "4.6 no Google, 35 avaliações — um pouco de tudo, e pessoas que o tratam bem.",
    reviewsOnGoogle: "Avaliações no Google",
    reviewsSummary: "Resumo das avaliações no Google",
    open: "Aberto",
    closed: "Fechado",
    closesAt: "Fecha às",
    opensAt: "Abre às",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    callShop: "Ligar para a loja",
    textShop: "Mensagem à loja",
    reviewsPeople: "As pessoas voltam",
    reviewsWrite: "Escrever uma avaliação no Google",
    reviewsGoogle: "Ver avaliações no Google",
    reviewsMore: "Mais avaliações",
    reviewsLess: "Menos avaliações",
    photosTitle: "Fotos",
    photosLede: "Corredores, o talho e o que está na prateleira esta semana.",
    photosAislesTitle: "Dentro da loja",
    photosCloseTitle: "Balcão e detalhes",
    pantryShotsTitle: "Marcas da despensa",
    pantryShotsLede:
      "Goya, Herdez, Embasa, Cacique, Ibarra, La Lechera — mercearia e o fresco que o bairro procura.",
    signAlt: "Letreiro do Latino Mini Market — mercearia, deli, talho. Produtos hispânicos, americanos e brasileiros.",
  },
} as const;

export function t(lang: Lang) {
  return COPY[lang];
}

export const DAY_LABELS: Record<Lang, string[]> = {
  en: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  es: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
  pt: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
};
